[package]
name = "rlox-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
rlox = { path = "../.." }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-std"] }
tower-lsp = "0.20"
